const express=require("express")
const server=express()
const getRoutes=require("./api/getRoutes")
const postRoutes=require("./api/postRoutes")
const mongoosecontact=require("./api/createContactData")
const getContact=require("./api/readContact")
const bp=require("body-parser")
server.use(bp.json())
server.use("/user",getRoutes)
server.use("/routePost",postRoutes)
server.use("/",mongoosecontact)
server.use("/",getContact)

server.listen(3001,()=>console.log("started"))